# Dependencies
gems:
  - jekyll-sitemap
  - jekyll-paginate

# Permalinks
permalink:           pretty

# Setup
url:                 www.google.com

# Set to '' in case of hosting on GitHub pages,
# i.e. `http://<username>.github.io`
baseurl:             ''

title:               De iure & tech

# Pagination
paginate:            5
paginate_path:       '/page-:num/'

# Markdown enabled, however don't use more than one paragraph (enforced by `>`)
description:         >
  Blog sobre derecho y nuevas tecnologías

# The tags listed as entries in the sidebar
sidebar_tags:        [protecciondedatos,derechotecnologico,marcas]

# Fallback image and color if not overwritten for tag or post
image:               /public/img/principal.jpg
color:               '#A85641'

# Fonts
font:                '"PT Serif", Georgia, serif'
font_accent:         '"Roboto Slab", "PT Serif", Georgia, serif'
load_google_fonts:   'Roboto+Slab:700|PT+Serif:400,400italic,700,700italic'

# About yourself
author:
  name:              'Maria Mitjans Serveto'

  # This photo will be used in the about section
  photo:             /public/img/me.jpg
  photo2x:           /public/img/me.jpg

  # Markdown enabled, can use multiple paragraphs (enabled by `|`)
  about:             |
   Me licencié en Derecho por la Universidad Pompeu Fabra y posteriormente cursé el máster en estudios jurídicos avanzados por la Universidad de Barcelona, donde me empecé a interesar por la protección de datos y el derecho de las nuevas tecnologías, un entorno cambiante lleno de retos a nivel legal. He complementado mi formación con diversos cursos sobre LOPD y contratos tecnológicos en el ICAB y me he formado como experta y auditora en protección de datos en la ApCpD. 

  # Social media icons in sidebar
  # Comment/uncommet to show/hide
  # Icons appear in order, can be rearranged:
  social:
    # facebook:        _username_
    twitter:         mariamitjanss
    # google:          _number_
    # vk:              _username_
    # youtube:         _string___string___string_
    # vimeo:           _username_
    # vine:            _username_
    # spotify:         user/_number_
    # soundcloud:      _username_
    # lastfm:          _username_
    # instagram:       _username_
    # flickr:          _string_@_string_
    # 500px:           _username_
    # dribbble:        _username_
    # behance:         _username_
    # deviantart:      _username_
    # ello:            _username_
    # twitch:          _username_
    # steam:           _number_
    # reddit:          _username_
    # tumblr:          _username_
    # pinterest:       _username_
    # foursquare:      _number_
    # yelp:            _string_
    # github:          _username_
    # stackoverflow:   _number_/_username_
    # npm:             _username_
    # hackernews:      _username_
    # trello:          _firstname__lastname_
    linkedin:        mariamitjans
    # xing:            _firstname___lastname__counter_
    # blogger:         _number_
    # delicious:       _username_
    # stumbleupon:     _username_
    # paypal:          _username_

# Remove to disable Google Anaylics
google_analytics_id: 'UA-92253463-1'

# Setting a disqus subdomain will enable the comment section
# disqus:            <username>

kramdown:
  math_engine:       mathjax
  math_engine_opts:
    preview:         true
    preview_as_code: true

compress_html:
  comments:          ["<!-- ", " -->"]
  clippings:         all
  endings:           all
  ignore:
    envs:            [local]

sass:
  style:             compressed

#Staticman
   comments:
 provider: "staticman"
   staticman:
 name                   : "Mitjans Serveto blog"
 allowedFields          : ['name', 'email', 'url', 'message']
 branch                 : "master"
 commitMessage          : "Nuevo comentario."
 filename               : comment-{@timestamp}
 format                 : "yml"
 moderation             : false
 path                   : "_data/comments/{options.slug}"
 requiredFields         : ['name', 'email', 'message']
 transforms:
   email                : "md5"
 generatedFields:
   date:
type               : "date"
options:
  format           : "iso8601"
comment            : true
